-- 360 Receipt Tracker — core schema, audit, RLS, and private Storage.
-- Mirrors the Asset Register patterns (security-definer history trigger +
-- editor-array RLS) already live in project inhwadbibwkakacdvoxu.
-- Idempotent: safe to re-run.

-- ---------------------------------------------------------------------------
-- Core table
-- ---------------------------------------------------------------------------
create table if not exists public.receipts (
  id               uuid primary key default gen_random_uuid(),
  receipt_date     date not null,
  vendor           text not null default '',
  amount           numeric(12,2) not null,
  currency         text not null default 'USD',
  company          text not null default 'Needs Coding',   -- company / reimbursement target
  category_code    text not null default '',
  comment          text not null default '',               -- business purpose
  reimbursable     boolean not null default true,
  status           text not null default 'ready'
                     check (status in ('ready','needs_coding','excluded','reported')),
  storage_bucket   text not null default 'receipts' check (storage_bucket = 'receipts'),
  storage_path     text not null default '',
  original_name    text not null default '',
  mime_type        text not null default '',
  byte_size        bigint not null default 0,
  sha256           text not null default '',
  ocr_raw          jsonb,
  source           text not null default 'portal' check (source in ('portal','outlook')),
  ledger_receipt_id text not null default '',              -- link to OneDrive ledger R-YYYY-MM-###
  synced_to_ledger boolean not null default false,
  created_by       uuid default auth.uid(),
  created_email    text not null default lower(coalesce(auth.jwt() ->> 'email','')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index if not exists receipts_date_idx    on public.receipts(receipt_date desc);
create index if not exists receipts_company_idx on public.receipts(company);
create index if not exists receipts_status_idx  on public.receipts(status, created_at desc);
create index if not exists receipts_sync_idx    on public.receipts(synced_to_ledger);

-- ---------------------------------------------------------------------------
-- Audit history
-- ---------------------------------------------------------------------------
create table if not exists public.receipt_history (
  id           bigint generated by default as identity primary key,
  receipt_id   uuid not null,
  op           text not null check (op in ('INSERT','UPDATE','DELETE')),
  actor_id     uuid,
  actor_email  text,
  changed_at   timestamptz not null default now(),
  changes      jsonb not null default '{}'::jsonb
);
create index if not exists receipt_history_receipt_idx
  on public.receipt_history(receipt_id, changed_at desc);

create or replace function public.log_receipt_change()
returns trigger language plpgsql security definer set search_path to 'public'
as $function$
declare diff jsonb;
begin
  if tg_op = 'UPDATE' then
    select coalesce(jsonb_object_agg(o.key, jsonb_build_object('from', o.value, 'to', n.value)), '{}'::jsonb)
      into diff
    from jsonb_each(to_jsonb(old)) o
    join jsonb_each(to_jsonb(new)) n on n.key = o.key
    where o.value is distinct from n.value
      and o.key not in ('updated_at','created_at');
    if diff = '{}'::jsonb then return new; end if;
    insert into public.receipt_history(receipt_id, op, actor_id, actor_email, changes)
      values (new.id, 'UPDATE', auth.uid(), lower(auth.jwt() ->> 'email'), diff);
    return new;
  elsif tg_op = 'INSERT' then
    insert into public.receipt_history(receipt_id, op, actor_id, actor_email, changes)
      values (new.id, 'INSERT', auth.uid(), lower(auth.jwt() ->> 'email'), to_jsonb(new));
    return new;
  else
    insert into public.receipt_history(receipt_id, op, actor_id, actor_email, changes)
      values (old.id, 'DELETE', auth.uid(), lower(auth.jwt() ->> 'email'), to_jsonb(old));
    return old;
  end if;
end
$function$;

drop trigger if exists trg_receipt_history on public.receipts;
create trigger trg_receipt_history
after insert or delete or update on public.receipts
for each row execute function public.log_receipt_change();

create or replace function public.touch_receipts_updated_at()
returns trigger language plpgsql as $function$
begin new.updated_at = now(); return new; end
$function$;

drop trigger if exists trg_receipts_touch on public.receipts;
create trigger trg_receipts_touch before update on public.receipts
for each row execute function public.touch_receipts_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security  (editors: jonj@ , margi@)
-- ---------------------------------------------------------------------------
alter table public.receipts enable row level security;
alter table public.receipt_history enable row level security;

drop policy if exists "auth read receipts" on public.receipts;
create policy "auth read receipts" on public.receipts
  for select to authenticated using (true);

drop policy if exists "editors insert receipts" on public.receipts;
create policy "editors insert receipts" on public.receipts
  for insert to authenticated
  with check (lower(auth.jwt() ->> 'email') = any (array['jonj@360-llc.com','margi@360-llc.com']));

drop policy if exists "editors update receipts" on public.receipts;
create policy "editors update receipts" on public.receipts
  for update to authenticated
  using (lower(auth.jwt() ->> 'email') = any (array['jonj@360-llc.com','margi@360-llc.com']))
  with check (lower(auth.jwt() ->> 'email') = any (array['jonj@360-llc.com','margi@360-llc.com']));

drop policy if exists "auth read receipt history" on public.receipt_history;
create policy "auth read receipt history" on public.receipt_history
  for select to authenticated using (true);

-- ---------------------------------------------------------------------------
-- Private Storage bucket + object policies
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('receipts','receipts', false, 26214400,
        array['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf'])
on conflict (id) do nothing;

drop policy if exists "auth read receipt objects" on storage.objects;
create policy "auth read receipt objects" on storage.objects
  for select to authenticated using (bucket_id = 'receipts');

drop policy if exists "editors upload receipt objects" on storage.objects;
create policy "editors upload receipt objects" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'receipts'
              and lower(auth.jwt() ->> 'email') = any (array['jonj@360-llc.com','margi@360-llc.com']));

-- ---------------------------------------------------------------------------
-- Table privileges for PostgREST roles.  REQUIRED: a raw `create table` does
-- NOT grant SELECT/INSERT/etc to anon/authenticated.  RLS gates *rows*, but the
-- role still needs the underlying GRANT or PostgREST returns
-- "permission denied for table".  Mirrors the live `assets` table grants.
-- ---------------------------------------------------------------------------
grant select, insert, update, delete on public.receipts to authenticated;
grant select on public.receipt_history to authenticated;
grant all on public.receipts to service_role;
grant all on public.receipt_history to service_role;
